services:
  - type: web
    name: eoos-backend
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        value: "file:./dev.db"
      - key: PORT
        value: "4000"
